routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//HomePage
Route::name('home.')->group(function(){
    Route::get('/','FrontEndController@listData');
    Route::get('navbar','FrontEndController@navBar');
    Route::get('/detail/{id}','FrontEndController@productDetail')->name('detail');
    Route::post('/addToCart','FrontendController@addToCart')->name('addtocart');
    Route::get('/cart','FrontendController@Cart')->name('cart');
    Route::get('/checkout','FrontendController@Checkout')->name('checkout');
    // Route::get('destroy/{id}', 'FrontendController@removeCart')->name('remove');
    Route::post('order_detail', 'FrontendController@orderDetail')->name('order_detail');
    Route::get('success/{order_id}/{customer_id}', 'FrontendController@Success')->name('success');
    Route::get('products/{id}', 'FrontendController@showProduct')->name('products');
    Route::get('brands/{id}', 'FrontendController@showBrand')->name('brands');
    Route::get('/search','FrontendController@search')->name('search');
    Route::post('/searchPost','FrontendController@searchByName')->name('searchpost');
    Route::get('/product/tab/{category_id}','FrontendController@productTab')->name('tab');
    Route::post('/updateCart','FrontendController@updateCart')->name('updateCart');
    Route::post('/removeCart','FrontendController@removeCart')->name('removeCart');

});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');


// URLadmin
Route::get('admin',function (){
    return view('admin.app');
});
Route::prefix('product')->group( function () {
    Route::name('product.')->group( function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
        Route::get('/show/{id}', 'ProductController@show')->name('show');
        Route::put('/update/{id}', 'ProductController@update')->name('update');
        Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');

    });
});

Route::prefix('category')->group( function () {
    Route::name('category.')->group( function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/create', 'CategoryController@create')->name('create');
    });
});
Route::prefix('manufacturers')->group( function () {
    Route::name('manufacturers.')->group( function () {
        Route::get('/', 'ManufacturersController@index')->name('index');
        Route::get('/edit/{id}', 'ManufacturersController@edit')->name('edit');
       
        Route::put('/update/{id}', 'ManufacturersController@update')->name('update');
        Route::get('/delete/{id}', 'ManufacturersController@destroy')->name('destroy');
        Route::post('/create', 'ManufacturersController@store')->name('store');
        Route::get('/create', 'ManufacturersController@create')->name('create');
    });
});
Route::prefix('customer')->group( function () {
    Route::name('customer.')->group( function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('edit');
        Route::get('/show/{id}', 'CustomerController@show')->name('show');
        Route::put('/update/{id}', 'CustomerController@update')->name('update');
        Route::get('/delete/{id}', 'CustomerController@destroy')->name('destroy');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/create', 'CustomerController@store')->name('store');

    });
});
Route::prefix('categorychild')->group( function () {
    Route::name('categorychild.')->group( function () {
        Route::get('/', 'CategoryChildrenController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryChildrenController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryChildrenController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryChildrenController@destroy')->name('destroy');
        Route::get('/create', 'CategoryChildrenController@create')->name('create');
        Route::post('/create', 'CategoryChildrenController@store')->name('store');

    });
});

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Categorychild;
use App\Customer;
use App\Manufacturers;
use App\Order;
use App\OrderDetail;
use Illuminate\Http\Request;
use App\Product;
use Illuminate\Support\Facades\DB;

class FrontendController extends Controller
{   
    protected $product;
    protected $orderDetail;
    protected $customer;
    protected $order;
    protected $categorychild;

    public function __construct(Category $category,Product $product,OrderDetail $orderDetail,Customer $customer, Order $order, Categorychild $categorychild)
    {
        $this->category  = $category;
        $this->product = $product;
        $this->orderDetail = $orderDetail;
        $this->customer = $customer;
        $this->order = $order;
        $this->categorychild = $categorychild;
        
    }
    public function listData()
    {
        $countProduct = DB::table('order_detail')->selectRaw('products_id, count(products_id) as topOrder')->groupBy('products_id')->orderBy('topOrder','DESC')->limit(12)->get();
        foreach($countProduct as $count){
            $productIdCountArr[] = $count->products_id; 
        }
        $topProduct = $this->product::whereIn('id',$productIdCountArr)->get();
        $manufacturers = Manufacturers::all();
        $categorychild = $this->categorychild::limit(3)->get();
        foreach($categorychild as $productMenu){
            $product = $this->product::where('categorychildren_id',$productMenu->id)->limit(5)->get();
            $productMenu->product = $product;
        }
        $categories = Category::limit(3)->get();
        $customers = $this->customer::all();
        $productRandom = $this->product::all()->random(10);
        $newProducts = Product::orderBy('id', 'DESC')->limit(10)->get();
        return view('frontend.page.home', compact([
            'newProducts', 'productRandom', 'categories',
            'manufacturers', 'customers', 'categorychild', 'topProduct'
        ]));
    }
    public function productTab($id)
    {
        if ($id == '*') {
            $products = $this->product::all()->random(12);
        } else {
            $products = $this->product::where('category_id', $id)->get();
        }
        // dd($products);
        foreach ($products as $product) {
            $product->image = str_replace('public', '', 'storage/' . $product->image);
            $product->price = number_format((float)$product->price, 0, '.', ',');
        }
        return response()->json($products, 200);
    }
    public function search()
    {
        return view('frontend.page.search');
    }
    public function searchByName(Request $request)
    {
        $data = [];
        $research = $this->product::where('name', 'like', '%' . $request->search . '%')->get();
        // dd(count($research));
        $data = [
            'search' => $research,
            'message' => '"' . count($research) . '" tìm thấy kết quả cho từ khoá"' . $request->search . '"'
        ];
        return view('frontend.page.search', compact('data'));
    }
    public function productDetail($id)
    {
        $product = $this->product::find($id);
        return view('frontend.page.productdetail', compact('product'));
    }
    public function addToCart(Request $request)
    {
        try {
            $total = 0;
            $product = $this->product::findOrFail($request->dataID);

            if (\Cart::count() == 0) {
                \Cart::add([
                    'id' => $request->dataID,
                    'name' => $product->name,
                    'qty' => $request->qty ? $request->qty : 1,
                    'price' => $product->price,
                    'weight' => 0,
                    'options' => [str_replace('public', '', 'storage' . $product->image)]
                ]);
                foreach (\Cart::content() as $cartItem) {
                    $total += $cartItem->qty * $cartItem->price;
                }
                return $this->jsonDataResult([
                    'cart' => \Cart::content(),
                        'total' => number_format($total,0,'.',','),
                        'count' => \Cart::count()
                ], 200);
            }

            $productByID = \Cart::content()->where('id', $request->dataID);
            
            if (count($productByID) > 0) {
                $total = 0;
                foreach ($productByID as $productByIdItem) {
                    $rowId = $productByIdItem->rowId;
                }
                if ($request->qty) {
                    $productByID[$rowId]->qty += $request->qty;
                } else {
                    $productByID[$rowId]->qty++;
                }
                foreach (\Cart::content() as $cartItem) {
                    $total += $cartItem->qty * $cartItem->price;
                }
                return $this->jsonDataResult([
                    'cart' => \Cart::content(),
                        'total' => number_format($total,0,'.',','),
                        'count' => \Cart::count()
                ], 200);
            }
            \Cart::add([
                'id' => $request->dataID,
                'name' => $product->name,
                'qty' => $request->qty ? $request->qty : 1,
                'price' => $product->price,
                'weight' => 0,
                'options' => [str_replace('public', '', 'storage' . $product->image)]
            ]);
            $total = 0;
            foreach (\Cart::content() as $cartItem) {
                $total += $cartItem->qty * $cartItem->price;
            }
            return $this->jsonDataResult([
                    'cart' => \Cart::content(),
                        'total' => number_format($total,0,'.',','),
                        'count' => \Cart::count()
            ], 200);
        } catch (\Exception $e) {
            return $this->jsonMsgResult($e->getMessage(),false,500);
        }
    }
    public function updateCart(Request $request)
    {
        $request->validate([
            'qty' => 'required|integer|min:0',
        ]);
        $total = 0;
        if ($request->dataID) {
            \Cart::content()[$request->dataID]->qty = $request->qty;
        }
        $subPrice = number_format(\Cart::content()[$request->dataID]->qty * \Cart::content()[$request->dataID]->price,0,'.',',').'đ';
        foreach (\Cart::content() as $cartItem) {
            $total += $cartItem->qty * $cartItem->price;
        }
        return $this->jsonDataResult([
            'subPrice' => $subPrice,
            'cart' => \Cart::content()[$request->dataID],
            'total' => number_format($total, 0, '.', ',') . 'đ'
        ],200);
    }
    public function Cart()
    {
        return view('frontend.page.cart');
    }
    public function removeCart(Request $request)
    {
        $total = 0;
        \Cart::remove($request->dataID);
        foreach(\Cart::content() as $cartItem){
            $total = $cartItem->qty * $cartItem->price;
        }
        return $this->jsonDataResult([
            'total' => $total,
            'count' => \Cart::count()
        ],200);
    }
    public function Checkout()
    {
        $total = 0;
        foreach (\Cart::content() as $cartItem) {
            $total += $cartItem->qty * $cartItem->price;
        }
        return view('frontend.page.checkout', compact('total'));
    }
    public function orderDetail(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'address' => 'required|string|max:255',
            'phone' => 'required',
            'note' => 'required',
        ]);
        $newCustomer = new $this->customer($request->all());
        $newCustomer->save();
        $newOrder = new $this->order();
        $newOrder->customers_id = $newCustomer->id;
        $newOrder->ordernumber = 'abc';
        $newOrder->save();
        $cartCollection = \Cart::content();
        foreach ($cartCollection as $product) {
            $orderDetail = new $this->OrderDetail();
            $orderDetail->products_id = (int) $product->id;
            $orderDetail->order_id = $newOrder->id;
            $orderDetail->ordernumber = 1;
            $orderDetail->price = $product->price;
            $orderDetail->quantity = $product->qty;
            $orderDetail->total = $product->qty * $product->price;
            $orderDetail->save();
        }
        return redirect()->route('home.success', ['order_id' => $newOrder->id, 'customer_id' => $newCustomer->id]);
    }
    public function Success($order_id, $customer_id)
    {
        $orderDetail = $this->OrderDetail::where('order_id', $order_id)->get();
        $totalPrice = 0;
        foreach ($orderDetail as $orderDetailByProduct) {
            $products = $this->product::where('id', $orderDetailByProduct->products_id)->get();
            $orderDetailByProduct->product = $products;
            $totalPrice += $orderDetailByProduct->quantity * $orderDetailByProduct->price;
        }
        $order = Order::where('customers_id', $customer_id)->get();
        foreach ($order as $orderItem) {
            $customerID = $orderItem->customers_id;
        }
        \Cart::destroy();

        $customer = $this->customer::find($customerID);
        return view('frontend.page.successCheckout', compact('totalPrice', 'orderDetail', 'customer'));
    }
    public function showProduct(Request $request, $id)
    {

        $products = $this->product::where('category_id', $id)->get();
        $categorychild = Categorychild::find($id);
        return view('frontend.page.products', compact(['products', 'categorychild']));
    }
    public function showBrand($id)
    {
        $products = $this->product::where('manufacturers_id', $id)->get();
        $brands = Manufacturers::find($id);
        return view('frontend.page.brands', compact(['brands', 'products']));
    }
    private function jsonMsgResult($errors, $success, $statusCode)
    {
        $result = [
            'errors' => $errors,

resources/views/frontend/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Smile | Responsive Bootstrap Ecommerce Template</title>

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="/favicon.ico">
    <!-- Google Webfont -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,100,300,300italic,700,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" integrity="sha512-wJgJNTBBkLit7ymC6vvzM1EcSWeM9mmOu+1USHaRBbHkm6W9EgM0HY27+UtUaprntaYQJF75rc8gjxllKs5OIQ==" crossorigin="anonymous" />
    <!-- CSS -->
    <link rel="stylesheet" href="{{asset('css/font-awesome/css/font-awesome.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('js/vendors/isotope/isotope.css')}}">
    <link rel="stylesheet" href="{{asset('js/vendors/slick/slick.css')}}">
    <link rel="stylesheet" href="{{asset('js/vendors/rs-plugin/css/settings.css')}}">
    <link rel="stylesheet" href="{{asset('js/vendors/select/jquery.selectBoxIt.css')}}">
    <link rel="stylesheet" href="{{asset('css/subscribe-better.css')}}">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/ui-lightness/jquery-ui.css">
    <link rel="stylesheet" href="{{asset('plugin/owl-carousel/owl.carousel.css')}}">
    <link rel="stylesheet" href="{{asset('plugin/owl-carousel/owl.theme.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
</head><!--/head-->

<body>
	@include('frontend.layout.header')
    @yield('content')
    @include('frontend.layout.footer')
    <script src="{{asset('js/jquery.js')}}"></script>

    <!-- ADDTHIS -->
    <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-557a95e76b3e51d9" async="async"></script>
    <script type="text/javascript">
        // Call this function once the rest of the document is loaded
        function loadAddThis() {
            addthis.init()
        }
    </script>

    <!-- ADDTHIS -->
    <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-557a95e76b3e51d9" async="async"></script>
    <script type="text/javascript">
        // Call this function once the rest of the document is loaded
        function loadAddThis() {
            addthis.init()
        }
    </script>

    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    <script src="{{asset('plugin/owl-carousel/owl.carousel.min.js')}}"></script>
    <script src="{{asset('js/bs-navbar.js')}}"></script>
    <script src="{{asset('js/vendors/isotope/isotope.pkgd.js')}}"></script>
    <script src="{{asset('js/vendors/slick/slick.min.js')}}"></script>
    <script src="{{asset('js/vendors/tweets/tweecool.min.js')}}"></script>
    <script src="{{asset('js/vendors/rs-plugin/js/jquery.themepunch.revolution.min.js')}}"></script>
    <script src="{{asset('js/vendors/rs-plugin/js/jquery.themepunch.tools.min.js')}}"></script>
    <script src="{{asset('js/jquery.sticky.js')}}"></script>
    <script src="{{asset('js/jquery.subscribe-better.js')}}"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script src="{{asset('js/vendors/select/jquery.selectBoxIt.min.js')}}"></script>
    <script src="{{asset('js/main.js')}}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js" integrity="sha512-zlWWyZq71UMApAjih4WkaRpikgY9Bz1oXIW5G0fED4vk14JjGlQ1UmkGM392jEULP8jbNMiwLWdM8Z87Hu88Fw==" crossorigin="anonymous"></script>
        <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
  
    @stack('scripts')
</body>
</html>

resources/views/frontend/layout/footer.blade.php
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3 widget-footer col-sm-3">
                <h5>About Store</h5>
                <img src="images/basic/logo-lite.png" class="img-responsive space10" alt="" />
                <p>Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus</p>
                <div class="clearfix"></div>
                <ul class="f-social">
                    <li>
                        <a href="https://www.facebook.com" class="fa fa-facebook"></a>
                    </li>
                    <li>
                        <a href="https://www.twitter.com" class="fa fa-twitter"></a>
                    </li>
                    <li>
                        <a href="https://feedburner.google.com" class="fa fa-rss"></a>
                    </li>
                    <li>
                        <a href="mailto:email@website.com" class="fa fa-envelope"></a>
                    </li>
                    <li>
                        <a href="https://www.pinterest.com" class="fa fa-pinterest"></a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com" class="fa fa-instagram"></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-3 widget-footer">
                <h5>Latest Tweets</h5>
                <div class="tweet-info">
                    <div id="twitterfeed"></div>
                </div>
            </div>
            <div class="col-md-3 col-sm-3 widget-footer">
                <h5>Product tags</h5>
                <ul class="widget-tags">
                    <li><a href="./categories-grid.html">fashion</a></li>
                    <li><a href="./categories-grid.html">sports</a></li>
                    <li><a href="./categories-grid.html">business</a></li>
                    <li><a href="./categories-grid.html">news</a></li>
                    <li><a href="./categories-grid.html">night</a></li>
                    <li><a href="./categories-grid.html">freedom</a></li>
                    <li><a href="./categories-grid.html">design</a></li>
                    <li><a href="./categories-grid.html">miracle</a></li>
                    <li><a href="./categories-grid.html">gallery</a></li>
                    <li><a href="./categories-grid.html">collection</a></li>
                    <li><a href="./categories-grid.html">pen</a></li>
                    <li><a href="./categories-grid.html">pants</a></li>
                    <li><a href="./categories-grid.html">jeans</a></li>
                    <li><a href="./categories-grid.html">photos</a></li>
                    <li><a href="./categories-grid.html">oscar</a></li>
                    <li><a href="./categories-grid.html">smile</a></li>
                    <li><a href="./categories-grid.html">love</a></li>
                    <li><a href="./categories-grid.html">sunshine</a></li>
                    <li><a href="./categories-grid.html">luxury</a></li>
                    <li><a href="./categories-grid.html">forever</a></li>
                    <li><a href="./categories-grid.html">inlove</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-3 widget-footer">
                <h5>Newsletter</h5>
                <p>Sign up for our newsletter and promotions</p>
                <form class="newsletter">
                    <input type="text" placeholder="Enter your email address here.">
                    <button type="submit">Subscribe !</button>
                </form>
            </div>
        </div>
    </div>
</footer>
<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-md-7 col-sm-7">
                <ul class="flinks">
                    <li><a href="./index.html">Site Map</a></li>
                    <li><a href="./index.html">Search Terms</a></li>
                    <li><a href="./index.html">Advanced Search</a></li>
                    <li><a href="./index.html">Orders and Returns</a></li>
                    <li><a href="./index.html">Customer Service</a></li>
                </ul>
                <br>
                <p>Copyright 2015 &middot; Designed & Developed by <a href="#">jThemes Studio.</a> All rights reserved</p>
            </div>
            <div class="col-md-5 col-sm-5">
                <img src="images/basic/payment.png" class="pull-right img-responsive payment" alt="" />
            </div>
        </div>
    </div>
</div>

resources/views/frontend/layout/header.blade.php
<div class="top_bar">
    @php($categories = App\Category::limit(3)->get())
    <div class="container">
        <div class="row">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="tb_left pull-left">
                        <p>Welcome to our online store !</p>
                    </div>
                    <div class="tb_center pull-left">
                        <ul>
                            <li>
                                <i class="fa fa-phone"></i> Hotline:
                                <a href="#">(+800) 2307 2509 8988</a>
                            </li>
                            <li>
                                <i class="fa fa-envelope-o"></i>
                                <a href="#">online support@smile.com</a>
                            </li>
                        </ul>
                    </div>
                    <div class="tb_right pull-right">
                        <ul>
                            <li>
                                
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- HEADER -->
<header>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="http://127.0.0.1:8000/"><img src="{{asset('images/basic/logo.png')}}" class="img-responsive" alt="" /></a>
                </div>
                <div class="header-xtra pull-right">
                    <div class="topcart">
                        <span>
                            <i class="fa fa-shopping-cart"></i>
                        </span>
                        <div class="cart-info">
                            <small>You have
                                <em class="highlight">{{\Cart::count()}} item(s)</em> in your
                                shopping bag</small>
                                <?php $total = 0; ?>
                            @foreach(\Cart::content() as $cart)
                                <?php $total += ($cart->qty * $cart->price) ?>
                                <div class="ci-item ciItem-{{$cart->rowId}}">
                                    <img src="{{asset($cart->options[0])}}" width="80" alt="" />
                                    <div class="ci-item-info">
                                        <h5>
                                            <a href="./single-product.html">{{$cart->name}}</a>
                                        </h5>
                                        <p>{{$cart->qty}} x {{number_format($cart->price)}}đ</p>
                                        {{-- <div class="ci-edit">
                                            <a href="#" class="edit fa fa-edit"></a>
                                            <a href="{{route('home.remove',['id'=>$cart->rowId])}}" class="edit fa fa-trash"></a>
                                        </div> --}}
                                    </div>
                                </div>
                            @endforeach
                            <div class="ci-total">Thành tiền: {{number_format($total)}} đ</div>
                            <div class="cart-btn">
                                <a href="{{route('home.cart')}}">Giỏ hàng</a>
                                <a href="{{route('home.checkout')}}">Thanh Toán</a>
                            </div>

                        </div>
                    </div>
                    <div class="topsearch">
                        <span>
                            <i class="fa fa-search"></i>
                        </span>
                        <form method="POST" action="{{route('home.searchpost')}}" class="searchtop">
                            @csrf
                            <input type="text" name="search" placeholder="Search entire store here." />
                        </form>
                    </div>
                </div>
                <!-- Navmenu -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown mmenu">
                            <a href="./categories-grid.html" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sản Phẩm</a>
                            <ul class="mega-menu dropdown-menu" role="menu">
                                @foreach($categories as $category)
                                    <li>
                                        <div>
                                        <a href="{{route('home.products',['id'=>$category->id])}}"><h5>{{$category->name}}</h5></a>
                                            @foreach($category->categorychild as $categorychildItem)
                                                <a href="{{route('home.products',['id'=>$categorychildItem->id])}}">{{$categorychildItem->name}}</a>
                                            @endforeach
                                        </div>
                                    </li>
                                @endforeach
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="./categories-grid.html" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Shop</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Blog</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pages</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>