routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//HomePage
Route::name('home.')->group(function(){
    Route::get('/','FrontEndController@listData');
    Route::get('navbar','FrontEndController@navBar');
    Route::get('/detail/{id}','FrontEndController@productDetail')->name('detail');
    Route::post('/addToCart','FrontendController@addToCart')->name('addtocart');
    Route::get('/cart','FrontendController@Cart')->name('cart');
    Route::get('/checkout','FrontendController@Checkout')->name('checkout');
    // Route::get('destroy/{id}', 'FrontendController@removeCart')->name('remove');
    Route::post('order_detail', 'FrontendController@orderDetail')->name('order_detail');
    Route::get('success/{order_id}/{customer_id}', 'FrontendController@Success')->name('success');
    Route::get('products/{id}', 'FrontendController@showProduct')->name('products');
    Route::get('brands/{id}', 'FrontendController@showBrand')->name('brands');
    Route::get('/search','FrontendController@search')->name('search');
    Route::post('/searchPost','FrontendController@searchByName')->name('searchpost');
    Route::get('/product/tab/{category_id}','FrontendController@productTab')->name('tab');
    Route::post('/updateCart','FrontendController@updateCart')->name('updateCart');
    Route::post('/removeCart','FrontendController@removeCart')->name('removeCart');

});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');


// URLadmin
Route::get('admin',function (){
    return view('admin.app');
});
Route::prefix('product')->group( function () {
    Route::name('product.')->group( function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
        Route::get('/show/{id}', 'ProductController@show')->name('show');
        Route::put('/update/{id}', 'ProductController@update')->name('update');
        Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');

    });
});

Route::prefix('category')->group( function () {
    Route::name('category.')->group( function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/create', 'CategoryController@create')->name('create');
    });
});
Route::prefix('manufacturers')->group( function () {
    Route::name('manufacturers.')->group( function () {
        Route::get('/', 'ManufacturersController@index')->name('index');
        Route::get('/edit/{id}', 'ManufacturersController@edit')->name('edit');
       
        Route::put('/update/{id}', 'ManufacturersController@update')->name('update');
        Route::get('/delete/{id}', 'ManufacturersController@destroy')->name('destroy');
        Route::post('/create', 'ManufacturersController@store')->name('store');
        Route::get('/create', 'ManufacturersController@create')->name('create');
    });
});
Route::prefix('customer')->group( function () {
    Route::name('customer.')->group( function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('edit');
        Route::get('/show/{id}', 'CustomerController@show')->name('show');
        Route::put('/update/{id}', 'CustomerController@update')->name('update');
        Route::get('/delete/{id}', 'CustomerController@destroy')->name('destroy');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/create', 'CustomerController@store')->name('store');

    });
});
Route::prefix('categorychild')->group( function () {
    Route::name('categorychild.')->group( function () {
        Route::get('/', 'CategoryChildrenController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryChildrenController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryChildrenController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryChildrenController@destroy')->name('destroy');
        Route::get('/create', 'CategoryChildrenController@create')->name('create');
        Route::post('/create', 'CategoryChildrenController@store')->name('store');

    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'id','name','description','price','image','categorychildren_id','manufacturers_id','checkbox','category_id'
    ];
    public function categorychild()
    {
        return $this->belongsTo('App\Categorychild','categorychildren_id');
    }
    public function category()
    {
        return $this->belongsTo('App\Category','category_id');
    }
    public function manufactures() {
        return $this->belongsTo('App\Manufacturers','manufacturers_id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Categorychild;
use App\Customer;
use App\Manufacturers;
use App\Product;
use Illuminate\Http\Request;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view ('admin.products.main',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $manufacturers = Manufacturers::all();
        $categorychild = Categorychild::all();
        $category = Category::all();
        return view ('admin.products.create',compact('manufacturers','categorychild','category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'image' => 'required',
            'price' => 'required',
            'checkbox' => 'required',
        ]);
        $path = null;
        $data = $request->all();
        $data['checkbox'] = $request->input('checkbox');
        if ($request->file('image')) {
            $path = $request->file('image')->store('public/products');
            $data['image'] = $path;
        }
        Product::create($data);
        return  redirect('/product')->with('message', 'Created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customers = Customer::all();
        $product = Product::find($id);
        // dd($product);
        return view ('admin.customers.main',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $manufacturers = Manufacturers::all();
        $product = Product::find($id);
        return view ('admin.products.edit',compact('product','manufacturers','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'image' => 'nullable',
        ]);

        $products = Product::find($id);

        $path = null;
        $data = $request->all();

        if ($request->file('image')) {
            $path = $request->file('image')->store('public/products');
            $data['image'] = $path;
        }
        $products->update($data);
        return redirect('/product');
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
   
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/products/create.blade.php
@extends('adminlte::page')

@section('title', 'Tao san pham moi')
@section('content')
    <h1 style="text-align: center">Create Products</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
    <form method="post" action="{{ route('product.store') }}" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input type="text" value="{{ old('name') }}" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Desc</label>
            <input type="text" value="{{ old('description') }}" name="description" class="form-control"  placeholder="Description">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Price</label>
            <input type="text" value="{{ old('price') }}" name="price" class="form-control"   placeholder="Price">
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">Image</label>
            <input type="file" name="image" class="form-control-file">
        </div>
        <div class="form-group">
            <input type="hidden" name="checkbox" value="0">
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">Category Child</label>
            <select name="categorychildren_id" class="form-control">
                @forelse($categorychild as $cate)
                <option value="{{ $cate->id }}">{{ $cate->name }}</option>
                @empty
                    <option>No data</option>
                @endforelse
            </select>
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">Manufacturers</label>
            <select name="manufacturers_id" class="form-control">
                @forelse($manufacturers as $manu)
                    <option value="{{ $manu->id }}">{{ $manu->name }}</option>
                @empty
                    <option>No data</option>
                @endforelse
            </select>
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">Category</label>
            <select name="category_id" class="form-control">
                @forelse($category as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                @empty
                    <option>No data</option>
                @endforelse
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@stop
@section('js')
    
@endsection

resources/views/admin/products/edit.blade.php
@extends('adminlte::page')

@section('title', 'Tao san pham moi')
@section('content')
    <h1 style="text-align: center">Edit Product</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
    <form method="post" action="{{ route('product.update',['id'=>$product->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input type="text" value="{{$product->name}}" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Desc</label>
            <input type="text" value="{{$product->description}}" name="description" class="form-control"  placeholder="Description">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Price</label>
            <input type="text" value="{{$product->price}}" name="price" class="form-control"   placeholder="Price">
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">Image</label>
            <input type="file" name="image" class="form-control-file">
            <div>
                <img width="120" src="{{ asset('storage/'. str_replace('public', '', $product->image))}}" alt="">
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Top Product</label> </br>
            <input type="hidden" name="checkbox" value="0">
            <input type="checkbox" name="checkbox" value="1" {{ ($product->checkbox == 1 ? ' checked' : '') }}>
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">The loai san pham</label>
            <select name="manufacturer_id" class="form-control" placeholder="manufacturer_id">
                @forelse($manufacturers as $mn)
                    <option  value="{{ $mn->id }}">{{ $mn->name }}</option>
                @empty
                    <option>No data</option>
                @endforelse
            </select>
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">The loai san pham</label>
            <select name="categories_id" class="form-control" placeholder="categories_id">
                @forelse($categories as $ct)
                    <option  value="{{$ct->id}}">{{ $ct->name }}</option>
                @empty
                    <option>No data</option>
                @endforelse
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@stop

resources/views/admin/products/main.blade.php
@extends('adminlte::page')

@section('title', 'Danh sach san pham')
@section('content')
    <h1 style="text-align: center">List Product</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Desc</th>
            <th scope="col">Price</th>
            <th scope="col">Image</th>
            <th scope="col">Manufacturersid</th>
            <th scope="col">Categoryid</th>
            <th scope="col">Type</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php  $stt = 1;?>

        @forelse($products as $pr)
            <tr>
                <th scope="row">{{ $stt }}</th>
                <td><a href="{{route('product.edit',['id'=>$pr->id])}}">{{$pr->name }}</a></td>
                <td>{{$pr->description }}</a></td>
                <td>{{$pr->price }}</a></td>
                <td><img width="120" src="{{ asset('storage/'. str_replace('public', '', $pr->image))}}" /></td>
                <td>{{ $pr->manufactures->name }}</td>
                <td>{{ $pr->category->name }}</td>
                <td>
                    <input type="hidden" id="inlineCheckbox1" name="my_checkbox[]" value="option1">
                    <input type="checkbox" id="inlineCheckbox2" name="my_checkbox[]" value="1" {{ ($pr->checkbox == 1 ? ' checked' : '') }}>
                </td>
                <td><a href="{{ route('product.destroy',['id'=>$pr->id])}}">Delete</a></td>
            </tr>
            <?php $stt++;?>
        @empty
        @endforelse
        </tbody>
    </table>
@stop