routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//HomePage
Route::name('home.')->group(function(){
    Route::get('/','FrontEndController@listData');
    Route::get('navbar','FrontEndController@navBar');
    Route::get('/detail/{id}','FrontEndController@productDetail')->name('detail');
    Route::post('/addToCart','FrontendController@addToCart')->name('addtocart');
    Route::get('/cart','FrontendController@Cart')->name('cart');
    Route::get('/checkout','FrontendController@Checkout')->name('checkout');
    // Route::get('destroy/{id}', 'FrontendController@removeCart')->name('remove');
    Route::post('order_detail', 'FrontendController@orderDetail')->name('order_detail');
    Route::get('success/{order_id}/{customer_id}', 'FrontendController@Success')->name('success');
    Route::get('products/{id}', 'FrontendController@showProduct')->name('products');
    Route::get('brands/{id}', 'FrontendController@showBrand')->name('brands');
    Route::get('/search','FrontendController@search')->name('search');
    Route::post('/searchPost','FrontendController@searchByName')->name('searchpost');
    Route::get('/product/tab/{category_id}','FrontendController@productTab')->name('tab');
    Route::post('/updateCart','FrontendController@updateCart')->name('updateCart');
    Route::post('/removeCart','FrontendController@removeCart')->name('removeCart');

});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');


// URLadmin
Route::get('admin',function (){
    return view('admin.app');
});
Route::prefix('product')->group( function () {
    Route::name('product.')->group( function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
        Route::get('/show/{id}', 'ProductController@show')->name('show');
        Route::put('/update/{id}', 'ProductController@update')->name('update');
        Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');

    });
});

Route::prefix('category')->group( function () {
    Route::name('category.')->group( function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/create', 'CategoryController@create')->name('create');
    });
});
Route::prefix('manufacturers')->group( function () {
    Route::name('manufacturers.')->group( function () {
        Route::get('/', 'ManufacturersController@index')->name('index');
        Route::get('/edit/{id}', 'ManufacturersController@edit')->name('edit');
       
        Route::put('/update/{id}', 'ManufacturersController@update')->name('update');
        Route::get('/delete/{id}', 'ManufacturersController@destroy')->name('destroy');
        Route::post('/create', 'ManufacturersController@store')->name('store');
        Route::get('/create', 'ManufacturersController@create')->name('create');
    });
});
Route::prefix('customer')->group( function () {
    Route::name('customer.')->group( function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('edit');
        Route::get('/show/{id}', 'CustomerController@show')->name('show');
        Route::put('/update/{id}', 'CustomerController@update')->name('update');
        Route::get('/delete/{id}', 'CustomerController@destroy')->name('destroy');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/create', 'CustomerController@store')->name('store');

    });
});
Route::prefix('categorychild')->group( function () {
    Route::name('categorychild.')->group( function () {
        Route::get('/', 'CategoryChildrenController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryChildrenController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryChildrenController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryChildrenController@destroy')->name('destroy');
        Route::get('/create', 'CategoryChildrenController@create')->name('create');
        Route::post('/create', 'CategoryChildrenController@store')->name('store');

    });
});

app/Categorychild.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorychild extends Model
{
    protected $guarded = [];
    protected $fillalbe = [
        'id','name','category_id'
    ];
    public $timestamps = false;
    public function products() {
        return $this->hasMany('App\Product','categorychildren_id');
    }
    public function category()
    {
        return $this->belongsTo('App\Category','category_id');
    }
}

resources/views/admin/categorychild/create.blade.php
@extends('adminlte::page')
@section('title', 'Tao san pham moi')
@section('content')
    <h1>Create Model Machine</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <form method="post" action="{{ route('categorychild.store') }}">
        @csrf
        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input type="text" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">category</label>
            <select name="category_id" class="form-control">
                @forelse($category as $cate)
                <option value="{{ $cate->id }}">{{ $cate->name }}</option>
                @empty
                    <option>No data</option>
                @endforelse
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@stop

resources/views/admin/categorychild/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit the loai')
@section('content')
    <h1>Edit Model Machine</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <form method="post" action="{{ route('categorychild.update', ['id' => $categorychild->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input type="text" value="{{$categorychild->name}}" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">category</label>
            <select name="category_id" class="form-control">
                @forelse($category as $cate)
                <option value="{{ $cate->id }}">{{ $cate->name }}</option>
                @empty
                    <option>No data</option>
                @endforelse
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@stop

resources/views/admin/categorychild/main.blade.php
@extends('adminlte::page')
@section('title', 'Danh sach the loai')
@section('content')
    <h1 style="text-align: center">List Model Machine</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Stt</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php  $stt = 1;?>
        @forelse($catechildren as $catechildren)
            <tr>
                <th scope="row">{{ $stt }}</th>
                <td><a href="{{route('categorychild.edit',['id' => $catechildren->id])}}">{{$catechildren->name }}</a></td>
                <td>{{ $catechildren->category->name }}</td>
                <td><a href="{{ route('categorychild.destroy',['id' => $catechildren->id]) }}">Delete</a></td>
            </tr>
            <?php $stt++;?>
        @empty
        @endforelse
        </tbody>
    </table>
@stop