routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//HomePage
Route::name('home.')->group(function(){
    Route::get('/','FrontEndController@listData');
    Route::get('navbar','FrontEndController@navBar');
    Route::get('/detail/{id}','FrontEndController@productDetail')->name('detail');
    Route::post('/addToCart','FrontendController@addToCart')->name('addtocart');
    Route::get('/cart','FrontendController@Cart')->name('cart');
    Route::get('/checkout','FrontendController@Checkout')->name('checkout');
    // Route::get('destroy/{id}', 'FrontendController@removeCart')->name('remove');
    Route::post('order_detail', 'FrontendController@orderDetail')->name('order_detail');
    Route::get('success/{order_id}/{customer_id}', 'FrontendController@Success')->name('success');
    Route::get('products/{id}', 'FrontendController@showProduct')->name('products');
    Route::get('brands/{id}', 'FrontendController@showBrand')->name('brands');
    Route::get('/search','FrontendController@search')->name('search');
    Route::post('/searchPost','FrontendController@searchByName')->name('searchpost');
    Route::get('/product/tab/{category_id}','FrontendController@productTab')->name('tab');
    Route::post('/updateCart','FrontendController@updateCart')->name('updateCart');
    Route::post('/removeCart','FrontendController@removeCart')->name('removeCart');

});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');


// URLadmin
Route::get('admin',function (){
    return view('admin.app');
});
Route::prefix('product')->group( function () {
    Route::name('product.')->group( function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
        Route::get('/show/{id}', 'ProductController@show')->name('show');
        Route::put('/update/{id}', 'ProductController@update')->name('update');
        Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');

    });
});

Route::prefix('category')->group( function () {
    Route::name('category.')->group( function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/create', 'CategoryController@create')->name('create');
    });
});
Route::prefix('manufacturers')->group( function () {
    Route::name('manufacturers.')->group( function () {
        Route::get('/', 'ManufacturersController@index')->name('index');
        Route::get('/edit/{id}', 'ManufacturersController@edit')->name('edit');
       
        Route::put('/update/{id}', 'ManufacturersController@update')->name('update');
        Route::get('/delete/{id}', 'ManufacturersController@destroy')->name('destroy');
        Route::post('/create', 'ManufacturersController@store')->name('store');
        Route::get('/create', 'ManufacturersController@create')->name('create');
    });
});
Route::prefix('customer')->group( function () {
    Route::name('customer.')->group( function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('edit');
        Route::get('/show/{id}', 'CustomerController@show')->name('show');
        Route::put('/update/{id}', 'CustomerController@update')->name('update');
        Route::get('/delete/{id}', 'CustomerController@destroy')->name('destroy');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/create', 'CustomerController@store')->name('store');

    });
});
Route::prefix('categorychild')->group( function () {
    Route::name('categorychild.')->group( function () {
        Route::get('/', 'CategoryChildrenController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryChildrenController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryChildrenController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryChildrenController@destroy')->name('destroy');
        Route::get('/create', 'CategoryChildrenController@create')->name('create');
        Route::post('/create', 'CategoryChildrenController@store')->name('store');

    });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
    protected $fillable = [
        'id','name'
    ];
    public function categorychild() {
        return $this->hasMany('App\Categorychild','category_id');
    }
    public function products() {
        return $this->hasMany('App\Product','category_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view ('admin.categories.main',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category($request->all());
        $category->save();
        return redirect('/category');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.categories.edit', compact('category'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required|string',
        ]);
        $category = Category::find($id);
        $category->update($request->all());
        return redirect('/category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')
@section('title', 'Tao san pham moi')
@section('content')
    <h1>Create Category</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
    <form method="post" action="{{route('category.store') }}">
        @csrf
        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input type="text" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@stop

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit the loai')
@section('content')
    <h1 style="text-align: center">Edit News</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <form method="post" action="{{ route('category.update', ['id' => $category->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="exampleInputEmail1 margin-left-3px">Name</label>
            <input type="text" value="{{$category->name}}" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <button type="submit" class="btn btn-primary margin-left-3px">Update Here</button>
    </form>
@stop

resources/views/admin/categories/main.blade.php
@extends('adminlte::page')
@section('title', 'Danh sach the loai')
@section('content')
    <h1 style="text-align: center ">List Category</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Stt</th>
            <th scope="col">Name</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php  $stt = 1;?>
        @forelse($categories as $c)
            <tr>
                <th scope="row">{{ $stt }}</th>
                <td><a href="{{route('category.edit',['id'=>$c->id])}}">{{$c->name }}</a></td>
                <td><a href="{{ route('category.destroy',['id'=>$c->id]) }}">Delete</a></td>
            </tr>
            <?php $stt++;?>
        @empty
        @endforelse
        </tbody>
    </table>
@stop